# Generated by Django 2.2.4 on 2019-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
